---
lucidity:
  awards:
    bonus_timer: 60
    timer_award: 150
    pose_multiplier: 10
    anonymous_chat: 10
    starting: 5000
  costs:
    describe_own_room: 500
    describe_other_room: 2500
    rename_own_room: 500
    build_room_base: 1500
    sympathetic_connection: 5000
    barrier_increase: 1000
    erect_bridge: 2500
    bridge_toll: 50
    details_home: 500
    details_other: 1000
    create_intradreamscape_exit: 1000
    ban_trespasser: 500
  starting_tokens:
    sympathy: 3
    bridge: 3
  words:
    illusion_start: 1500
